-- Sample Reports for CMMS System

-- Insert sample reports with various statuses and scenarios
INSERT INTO reports (id, reporter_id, breakdown_type, description, safety_required, assistance_required, location_method, sector, grid_location, machine_id, image_url, status, assigned_to, sla_timer, escalated, created_at, completed_at, updated_at) VALUES 

-- Recent Reports (Last 7 days)
(uuid_generate_v4(), 
 (SELECT id FROM users WHERE employee_id = 'WORK001'), 
 'mechanical', 
 'Conveyor belt A1 is making unusual grinding noise and vibrating excessively. The belt appears to be misaligned and may need immediate attention to prevent further damage.',
 false, 
 false, 
 'qr', 
 'Production Line A', 
 NULL,
 (SELECT id FROM machine_map WHERE qr_code_value = 'QR_PROD_A_001'),
 '/uploads/reports/conveyor_belt_issue_001.jpg',
 'working',
 (SELECT id FROM users WHERE employee_id = 'TECH001'),
 NOW() + INTERVAL '4 hours',
 false,
 NOW() - INTERVAL '2 hours',
 NULL,
 NOW() - INTERVAL '1 hour'),

(uuid_generate_v4(), 
 (SELECT id FROM users WHERE employee_id = 'WORK002'), 
 'electrical', 
 'Hydraulic press B1 electrical panel showing error code E-204. The machine stops mid-cycle and requires manual reset. This is affecting production schedule.',
 true, 
 true, 
 'qr', 
 'Production Line B', 
 NULL,
 (SELECT id FROM machine_map WHERE qr_code_value = 'QR_PROD_B_001'),
 '/uploads/reports/hydraulic_press_error_001.jpg',
 'noticed',
 NULL,
 NOW() + INTERVAL '2 hours',
 false,
 NOW() - INTERVAL '1 hour',
 NULL,
 NOW() - INTERVAL '1 hour'),

(uuid_generate_v4(), 
 (SELECT id FROM users WHERE employee_id = 'WORK003'), 
 'mechanical', 
 'CNC Machine C1 spindle bearing is making loud noise during operation. Vibration levels are higher than normal. Recommend immediate inspection.',
 false, 
 true, 
 'qr', 
 'Production Line C', 
 NULL,
 (SELECT id FROM machine_map WHERE qr_code_value = 'QR_PROD_C_001'),
 NULL,
 'working',
 (SELECT id FROM users WHERE employee_id = 'TECH002'),
 NOW() + INTERVAL '6 hours',
 false,
 NOW() - INTERVAL '3 hours',
 NULL,
 NOW() - INTERVAL '30 minutes'),

(uuid_generate_v4(), 
 (SELECT id FROM users WHERE employee_id = 'WORK004'), 
 'other', 
 'Packaging machine 1 label applicator is not functioning properly. Labels are being applied crooked and some packages are missing labels entirely.',
 false, 
 false, 
 'qr', 
 'Packaging', 
 NULL,
 (SELECT id FROM machine_map WHERE qr_code_value = 'QR_PACK_001'),
 '/uploads/reports/labeling_issue_001.jpg',
 'completed',
 (SELECT id FROM users WHERE employee_id = 'TECH003'),
 NOW() - INTERVAL '2 hours',
 false,
 NOW() - INTERVAL '6 hours',
 NOW() - INTERVAL '1 hour',
 NOW() - INTERVAL '1 hour'),

(uuid_generate_v4(), 
 (SELECT id FROM users WHERE employee_id = 'WORK005'), 
 'electrical', 
 'Quality control optical inspection system is showing intermittent connection errors. System reboots randomly during inspection cycles.',
 false, 
 false, 
 'qr', 
 'Quality Control', 
 NULL,
 (SELECT id FROM machine_map WHERE qr_code_value = 'QR_QC_002'),
 NULL,
 'working',
 (SELECT id FROM users WHERE employee_id = 'TECH004'),
 NOW() + INTERVAL '5 hours',
 false,
 NOW() - INTERVAL '4 hours',
 NULL,
 NOW() - INTERVAL '2 hours'),

-- Overdue Reports (for testing escalation)
(uuid_generate_v4(), 
 (SELECT id FROM users WHERE employee_id = 'WORK006'), 
 'mechanical', 
 'Forklift 1 hydraulic system is leaking fluid. Large puddle forming under the vehicle. Safety concern for slip hazard.',
 true, 
 false, 
 'qr', 
 'Warehouse', 
 NULL,
 (SELECT id FROM machine_map WHERE qr_code_value = 'QR_WARE_001'),
 '/uploads/reports/forklift_leak_001.jpg',
 'noticed',
 NULL,
 NOW() - INTERVAL '3 hours',
 true,
 NOW() - INTERVAL '5 hours',
 NULL,
 NOW() - INTERVAL '5 hours'),

(uuid_generate_v4(), 
 (SELECT id FROM users WHERE employee_id = 'WORK007'), 
 'electrical', 
 'Main air compressor electrical panel showing overheating warning. Temperature gauge in red zone. Immediate attention required.',
 true, 
 true, 
 'qr', 
 'Utilities', 
 NULL,
 (SELECT id FROM machine_map WHERE qr_code_value = 'QR_UTIL_001'),
 NULL,
 'working',
 (SELECT id FROM users WHERE employee_id = 'TECH005'),
 NOW() - INTERVAL '1 hour',
 true,
 NOW() - INTERVAL '4 hours',
 NULL,
 NOW() - INTERVAL '2 hours'),

-- Grid Location Reports (without QR codes)
(uuid_generate_v4(), 
 (SELECT id FROM users WHERE employee_id = 'WORK008'), 
 'other', 
 'Water leak detected in grid location UT-07. Water pooling around water treatment system. Possible pipe joint failure.',
 false, 
 false, 
 'grid', 
 'Utilities', 
 'UT-07',
 NULL,
 '/uploads/reports/water_leak_001.jpg',
 'noticed',
 NULL,
 NOW() + INTERVAL '6 hours',
 false,
 NOW() - INTERVAL '2 hours',
 NULL,
 NOW() - INTERVAL '2 hours'),

(uuid_generate_v4(), 
 (SELECT id FROM users WHERE employee_id = 'WORK009'), 
 'mechanical', 
 'Unusual vibration and noise coming from grid location A2-03. Possible bearing failure in assembly station A2.',
 false, 
 true, 
 'grid', 
 'Production Line A', 
 'A2-03',
 NULL,
 NULL,
 'working',
 (SELECT id FROM users WHERE employee_id = 'TECH006'),
 NOW() + INTERVAL '7 hours',
 false,
 NOW() - INTERVAL '1 hour',
 NULL,
 NOW() - INTERVAL '30 minutes'),

-- Completed Reports (for statistics)
(uuid_generate_v4(), 
 (SELECT id FROM users WHERE employee_id = 'WORK010'), 
 'mechanical', 
 'Welding station B1 gas regulator was not maintaining consistent pressure. Replaced faulty regulator and tested system.',
 false, 
 false, 
 'qr', 
 'Production Line B', 
 NULL,
 (SELECT id FROM machine_map WHERE qr_code_value = 'QR_PROD_B_003'),
 NULL,
 'completed',
 (SELECT id FROM users WHERE employee_id = 'TECH007'),
 NOW() - INTERVAL '10 hours',
 false,
 NOW() - INTERVAL '24 hours',
 NOW() - INTERVAL '12 hours',
 NOW() - INTERVAL '12 hours'),

(uuid_generate_v4(), 
 (SELECT id FROM users WHERE employee_id = 'WORK001'), 
 'electrical', 
 'Proximity sensor on packaging line was giving false readings. Cleaned sensor face and adjusted mounting position. System now operating normally.',
 false, 
 false, 
 'qr', 
 'Packaging', 
 NULL,
 (SELECT id FROM machine_map WHERE qr_code_value = 'QR_PACK_003'),
 '/uploads/reports/sensor_cleaning_001.jpg',
 'completed',
 (SELECT id FROM users WHERE employee_id = 'TECH008'),
 NOW() - INTERVAL '18 hours',
 false,
 NOW() - INTERVAL '30 hours',
 NOW() - INTERVAL '20 hours',
 NOW() - INTERVAL '20 hours'),

(uuid_generate_v4(), 
 (SELECT id FROM users WHERE employee_id = 'WORK002'), 
 'mechanical', 
 'Lathe machine C1 chuck was not gripping workpieces properly. Cleaned and lubricated chuck mechanism. Adjusted jaw pressure.',
 false, 
 false, 
 'qr', 
 'Production Line C', 
 NULL,
 (SELECT id FROM machine_map WHERE qr_code_value = 'QR_PROD_C_002'),
 NULL,
 'completed',
 (SELECT id FROM users WHERE employee_id = 'TECH001'),
 NOW() - INTERVAL '25 hours',
 false,
 NOW() - INTERVAL '36 hours',
 NOW() - INTERVAL '28 hours',
 NOW() - INTERVAL '28 hours'),

-- Archived Reports (older completed reports)
(uuid_generate_v4(), 
 (SELECT id FROM users WHERE employee_id = 'WORK003'), 
 'other', 
 'HVAC Unit 1 filter replacement was overdue. Replaced air filter and cleaned intake vents. System airflow restored to normal.',
 false, 
 false, 
 'qr', 
 'Utilities', 
 NULL,
 (SELECT id FROM machine_map WHERE qr_code_value = 'QR_UTIL_008'),
 NULL,
 'archived',
 (SELECT id FROM users WHERE employee_id = 'TECH002'),
 NOW() - INTERVAL '72 hours',
 false,
 NOW() - INTERVAL '168 hours',
 NOW() - INTERVAL '120 hours',
 NOW() - INTERVAL '120 hours'),

(uuid_generate_v4(), 
 (SELECT id FROM users WHERE employee_id = 'WORK004'), 
 'mechanical', 
 'Overhead crane in warehouse was making grinding noise during operation. Lubricated all grease points and adjusted cable tension.',
 false, 
 true, 
 'qr', 
 'Warehouse', 
 NULL,
 (SELECT id FROM machine_map WHERE qr_code_value = 'QR_WARE_005'),
 '/uploads/reports/crane_maintenance_001.jpg',
 'archived',
 (SELECT id FROM users WHERE employee_id = 'TECH003'),
 NOW() - INTERVAL '96 hours',
 false,
 NOW() - INTERVAL '192 hours',
 NOW() - INTERVAL '144 hours',
 NOW() - INTERVAL '144 hours'),

-- High Priority Safety Reports
(uuid_generate_v4(), 
 (SELECT id FROM users WHERE employee_id = 'WORK005'), 
 'electrical', 
 'Emergency generator electrical panel showing arc flash warning. Burning smell detected. IMMEDIATE SAFETY CONCERN - Area evacuated.',
 true, 
 true, 
 'qr', 
 'Utilities', 
 NULL,
 (SELECT id FROM machine_map WHERE qr_code_value = 'QR_UTIL_006'),
 '/uploads/reports/emergency_generator_001.jpg',
 'working',
 (SELECT id FROM users WHERE employee_id = 'TECH004'),
 NOW() + INTERVAL '1 hour',
 false,
 NOW() - INTERVAL '30 minutes',
 NULL,
 NOW() - INTERVAL '15 minutes'),

(uuid_generate_v4(), 
 (SELECT id FROM users WHERE employee_id = 'WORK006'), 
 'mechanical', 
 'Grinding machine B2 safety guard is loose and vibrating. Guard could potentially fail during operation. Safety hazard for operator.',
 true, 
 false, 
 'qr', 
 'Production Line B', 
 NULL,
 (SELECT id FROM machine_map WHERE qr_code_value = 'QR_PROD_B_008'),
 NULL,
 'noticed',
 NULL,
 NOW() + INTERVAL '1.5 hours',
 false,
 NOW() - INTERVAL '45 minutes',
 NULL,
 NOW() - INTERVAL '45 minutes'),

-- Reports requiring team assistance
(uuid_generate_v4(), 
 (SELECT id FROM users WHERE employee_id = 'WORK007'), 
 'mechanical', 
 'Palletizing robot requires major component replacement. Heavy lifting and specialized tools needed. Multi-technician job.',
 false, 
 true, 
 'qr', 
 'Packaging', 
 NULL,
 (SELECT id FROM machine_map WHERE qr_code_value = 'QR_PACK_007'),
 '/uploads/reports/robot_repair_001.jpg',
 'working',
 (SELECT id FROM users WHERE employee_id = 'TECH005'),
 NOW() + INTERVAL '8 hours',
 false,
 NOW() - INTERVAL '2 hours',
 NULL,
 NOW() - INTERVAL '1 hour'),

(uuid_generate_v4(), 
 (SELECT id FROM users WHERE employee_id = 'WORK008'), 
 'electrical', 
 'Coordinate measuring machine requires calibration and electrical troubleshooting. Complex diagnostic equipment needed.',
 false, 
 true, 
 'qr', 
 'Quality Control', 
 NULL,
 (SELECT id FROM machine_map WHERE qr_code_value = 'QR_QC_001'),
 NULL,
 'noticed',
 NULL,
 NOW() + INTERVAL '6 hours',
 false,
 NOW() - INTERVAL '3 hours',
 NULL,
 NOW() - INTERVAL '3 hours'),

-- Recent completed reports for performance metrics
(uuid_generate_v4(), 
 (SELECT id FROM users WHERE employee_id = 'WORK009'), 
 'other', 
 'Routine maintenance completed on cooling tower. Cleaned heat exchanger coils and checked water treatment chemical levels.',
 false, 
 false, 
 'qr', 
 'Utilities', 
 NULL,
 (SELECT id FROM machine_map WHERE qr_code_value = 'QR_UTIL_003'),
 NULL,
 'completed',
 (SELECT id FROM users WHERE employee_id = 'TECH006'),
 NOW() - INTERVAL '8 hours',
 false,
 NOW() - INTERVAL '12 hours',
 NOW() - INTERVAL '4 hours',
 NOW() - INTERVAL '4 hours'),

(uuid_generate_v4(), 
 (SELECT id FROM users WHERE employee_id = 'WORK010'), 
 'mechanical', 
 'Replaced worn cutting tools on milling machine C1. Adjusted spindle speed and feed rates for optimal performance.',
 false, 
 false, 
 'qr', 
 'Production Line C', 
 NULL,
 (SELECT id FROM machine_map WHERE qr_code_value = 'QR_PROD_C_003'),
 '/uploads/reports/tool_replacement_001.jpg',
 'completed',
 (SELECT id FROM users WHERE employee_id = 'TECH007'),
 NOW() - INTERVAL '6 hours',
 false,
 NOW() - INTERVAL '8 hours',
 NOW() - INTERVAL '2 hours',
 NOW() - INTERVAL '2 hours');

-- Display inserted reports count
SELECT 'Reports inserted: ' || COUNT(*) as result FROM reports;

