-- Sample Part Requests for CMMS System

INSERT INTO part_requests (id, technician_id, part_id, quantity_requested, quantity_approved, reason, status, requested_at, approved_at, approved_by, delivered_at, notes, created_at, updated_at) VALUES 

-- Recent Pending Requests
(uuid_generate_v4(),
 (SELECT id FROM users WHERE employee_id = 'TECH001'),
 (SELECT id FROM parts WHERE part_number = 'BLT-001'),
 2,
 NULL,
 'Need replacement conveyor belts for Production Line A. Current belts showing signs of wear and may fail soon.',
 'requested',
 NOW() - INTERVAL '2 hours',
 NULL,
 NULL,
 NULL,
 NULL,
 NOW() - INTERVAL '2 hours',
 NOW() - INTERVAL '2 hours'),

(uuid_generate_v4(),
 (SELECT id FROM users WHERE employee_id = 'TECH002'),
 (SELECT id FROM parts WHERE part_number = 'HYD-001'),
 1,
 NULL,
 'Hydraulic press B1 seal kit replacement required for ongoing repair. Current seals are leaking.',
 'requested',
 NOW() - INTERVAL '1 hour',
 NULL,
 NULL,
 NULL,
 NULL,
 NOW() - INTERVAL '1 hour',
 NOW() - INTERVAL '1 hour'),

(uuid_generate_v4(),
 (SELECT id FROM users WHERE employee_id = 'TECH003'),
 (SELECT id FROM parts WHERE part_number = 'BRG-001'),
 4,
 NULL,
 'Ball bearings needed for packaging machine maintenance. Scheduled preventive maintenance requires bearing replacement.',
 'requested',
 NOW() - INTERVAL '3 hours',
 NULL,
 NULL,
 NULL,
 NULL,
 NOW() - INTERVAL '3 hours',
 NOW() - INTERVAL '3 hours'),

(uuid_generate_v4(),
 (SELECT id FROM users WHERE employee_id = 'TECH004'),
 (SELECT id FROM parts WHERE part_number = 'ELC-002'),
 6,
 NULL,
 'Control relays for electrical panel repair in Quality Control. Multiple relays showing signs of contact wear.',
 'requested',
 NOW() - INTERVAL '4 hours',
 NULL,
 NULL,
 NULL,
 NULL,
 NOW() - INTERVAL '4 hours',
 NOW() - INTERVAL '4 hours'),

(uuid_generate_v4(),
 (SELECT id FROM users WHERE employee_id = 'TECH005'),
 (SELECT id FROM parts WHERE part_number = 'FLT-001'),
 8,
 NULL,
 'Oil filter cartridges for routine maintenance on multiple machines. Monthly filter replacement schedule.',
 'requested',
 NOW() - INTERVAL '30 minutes',
 NULL,
 NULL,
 NULL,
 NULL,
 NOW() - INTERVAL '30 minutes',
 NOW() - INTERVAL '30 minutes'),

-- Approved Requests (awaiting delivery)
(uuid_generate_v4(),
 (SELECT id FROM users WHERE employee_id = 'TECH006'),
 (SELECT id FROM parts WHERE part_number = 'MTR-002'),
 1,
 1,
 'Replacement motor for CNC machine C2. Current motor showing signs of overheating and reduced performance.',
 'approved',
 NOW() - INTERVAL '6 hours',
 NOW() - INTERVAL '4 hours',
 (SELECT id FROM users WHERE employee_id = 'TL001'),
 NULL,
 'Approved for immediate replacement. High priority due to production impact.',
 NOW() - INTERVAL '6 hours',
 NOW() - INTERVAL '4 hours'),

(uuid_generate_v4(),
 (SELECT id FROM users WHERE employee_id = 'TECH007'),
 (SELECT id FROM parts WHERE part_number = 'HYD-004'),
 10,
 8,
 'Hydraulic hoses for various maintenance tasks. Multiple machines require hose replacement.',
 'approved',
 NOW() - INTERVAL '8 hours',
 NOW() - INTERVAL '6 hours',
 (SELECT id FROM users WHERE employee_id = 'TL002'),
 NULL,
 'Approved 8 meters instead of 10. Sufficient for current needs.',
 NOW() - INTERVAL '8 hours',
 NOW() - INTERVAL '6 hours'),

(uuid_generate_v4(),
 (SELECT id FROM users WHERE employee_id = 'TECH008'),
 (SELECT id FROM parts WHERE part_number = 'CUT-001'),
 3,
 3,
 'End mills for machining operations. Current tools are worn and affecting part quality.',
 'approved',
 NOW() - INTERVAL '5 hours',
 NOW() - INTERVAL '3 hours',
 (SELECT id FROM users WHERE employee_id = 'TL001'),
 NULL,
 'Approved. Quality issue requires immediate tool replacement.',
 NOW() - INTERVAL '5 hours',
 NOW() - INTERVAL '3 hours'),

-- Delivered Requests (completed)
(uuid_generate_v4(),
 (SELECT id FROM users WHERE employee_id = 'TECH001'),
 (SELECT id FROM parts WHERE part_number = 'GSK-001'),
 2,
 2,
 'O-ring kits for hydraulic system maintenance. Preventive maintenance on multiple hydraulic units.',
 'delivered',
 NOW() - INTERVAL '24 hours',
 NOW() - INTERVAL '20 hours',
 (SELECT id FROM users WHERE employee_id = 'TL002'),
 NOW() - INTERVAL '18 hours',
 'Delivered to maintenance workshop. Technician confirmed receipt.',
 NOW() - INTERVAL '24 hours',
 NOW() - INTERVAL '18 hours'),

(uuid_generate_v4(),
 (SELECT id FROM users WHERE employee_id = 'TECH002'),
 (SELECT id FROM parts WHERE part_number = 'FST-001'),
 20,
 20,
 'High tensile bolts for structural repairs on packaging equipment. Safety-critical fasteners.',
 'delivered',
 NOW() - INTERVAL '30 hours',
 NOW() - INTERVAL '26 hours',
 (SELECT id FROM users WHERE employee_id = 'TL001'),
 NOW() - INTERVAL '24 hours',
 'Delivered complete quantity. Used for safety-critical repairs.',
 NOW() - INTERVAL '30 hours',
 NOW() - INTERVAL '24 hours'),

(uuid_generate_v4(),
 (SELECT id FROM users WHERE employee_id = 'TECH003'),
 (SELECT id FROM parts WHERE part_number = 'LUB-001'),
 3,
 3,
 'Machine oil for routine lubrication schedule. Monthly maintenance requirements.',
 'delivered',
 NOW() - INTERVAL '36 hours',
 NOW() - INTERVAL '32 hours',
 (SELECT id FROM users WHERE employee_id = 'TL002'),
 NOW() - INTERVAL '30 hours',
 'Delivered to maintenance area. Used for scheduled lubrication.',
 NOW() - INTERVAL '36 hours',
 NOW() - INTERVAL '30 hours'),

(uuid_generate_v4(),
 (SELECT id FROM users WHERE employee_id = 'TECH004'),
 (SELECT id FROM parts WHERE part_number = 'WLD-001'),
 4,
 4,
 'Welding rods for repair work on production equipment. Various welding repairs needed.',
 'delivered',
 NOW() - INTERVAL '48 hours',
 NOW() - INTERVAL '44 hours',
 (SELECT id FROM users WHERE employee_id = 'TL001'),
 NOW() - INTERVAL '42 hours',
 'Delivered to welding station. Used for equipment repairs.',
 NOW() - INTERVAL '48 hours',
 NOW() - INTERVAL '42 hours'),

-- Rejected Requests
(uuid_generate_v4(),
 (SELECT id FROM users WHERE employee_id = 'TECH005'),
 (SELECT id FROM parts WHERE part_number = 'MTR-001'),
 2,
 0,
 'Requested spare motors for inventory. Want to have backup motors available.',
 'rejected',
 NOW() - INTERVAL '72 hours',
 NOW() - INTERVAL '68 hours',
 (SELECT id FROM users WHERE employee_id = 'TL002'),
 NULL,
 'Rejected. No immediate need identified. Current motors in good condition.',
 NOW() - INTERVAL '72 hours',
 NOW() - INTERVAL '68 hours'),

(uuid_generate_v4(),
 (SELECT id FROM users WHERE employee_id = 'TECH006'),
 (SELECT id FROM parts WHERE part_number = 'CUT-002'),
 5,
 0,
 'Carbide end mills for general machining. Requested for tool crib stock.',
 'rejected',
 NOW() - INTERVAL '96 hours',
 NOW() - INTERVAL '92 hours',
 (SELECT id FROM users WHERE employee_id = 'TL001'),
 NULL,
 'Rejected. Current HSS tools adequate for current jobs. Carbide not justified.',
 NOW() - INTERVAL '96 hours',
 NOW() - INTERVAL '92 hours'),

-- Emergency/Urgent Requests
(uuid_generate_v4(),
 (SELECT id FROM users WHERE employee_id = 'TECH007'),
 (SELECT id FROM parts WHERE part_number = 'LOW-001'),
 1,
 1,
 'URGENT: Emergency repair kit needed for critical equipment failure. Production line down.',
 'approved',
 NOW() - INTERVAL '1 hour',
 NOW() - INTERVAL '45 minutes',
 (SELECT id FROM users WHERE employee_id = 'TL001'),
 NULL,
 'URGENT APPROVAL: Critical production equipment failure. Immediate delivery required.',
 NOW() - INTERVAL '1 hour',
 NOW() - INTERVAL '45 minutes'),

(uuid_generate_v4(),
 (SELECT id FROM users WHERE employee_id = 'TECH008'),
 (SELECT id FROM parts WHERE part_number = 'SAF-001'),
 10,
 10,
 'Safety glasses replacement after damage incident. Required for safety compliance.',
 'delivered',
 NOW() - INTERVAL '12 hours',
 NOW() - INTERVAL '10 hours',
 (SELECT id FROM users WHERE employee_id = 'TL002'),
 NOW() - INTERVAL '8 hours',
 'Safety priority delivery. Immediate replacement for damaged PPE.',
 NOW() - INTERVAL '12 hours',
 NOW() - INTERVAL '8 hours'),

-- Bulk Requests
(uuid_generate_v4(),
 (SELECT id FROM users WHERE employee_id = 'TECH001'),
 (SELECT id FROM parts WHERE part_number = 'FST-004'),
 50,
 40,
 'Washers for quarterly maintenance program. Large quantity needed for multiple machines.',
 'delivered',
 NOW() - INTERVAL '168 hours',
 NOW() - INTERVAL '160 hours',
 (SELECT id FROM users WHERE employee_id = 'TL001'),
 NOW() - INTERVAL '156 hours',
 'Approved 40 pieces. Sufficient for quarterly maintenance schedule.',
 NOW() - INTERVAL '168 hours',
 NOW() - INTERVAL '156 hours'),

(uuid_generate_v4(),
 (SELECT id FROM users WHERE employee_id = 'TECH002'),
 (SELECT id FROM parts WHERE part_number = 'LUB-004'),
 15,
 12,
 'Penetrating oil for maintenance operations. Used frequently for stuck bolts and parts.',
 'delivered',
 NOW() - INTERVAL '192 hours',
 NOW() - INTERVAL '184 hours',
 (SELECT id FROM users WHERE employee_id = 'TL002'),
 NOW() - INTERVAL '180 hours',
 'Approved 12 cans. Adequate for monthly consumption.',
 NOW() - INTERVAL '192 hours',
 NOW() - INTERVAL '180 hours'),

-- Recent requests for different technicians (for workload analysis)
(uuid_generate_v4(),
 (SELECT id FROM users WHERE employee_id = 'TECH003'),
 (SELECT id FROM parts WHERE part_number = 'BRG-002'),
 2,
 NULL,
 'Bearing replacement for assembly station A2. Bearing showing signs of wear.',
 'requested',
 NOW() - INTERVAL '6 hours',
 NULL,
 NULL,
 NULL,
 NULL,
 NOW() - INTERVAL '6 hours',
 NOW() - INTERVAL '6 hours'),

(uuid_generate_v4(),
 (SELECT id FROM users WHERE employee_id = 'TECH004'),
 (SELECT id FROM parts WHERE part_number = 'ELC-003'),
 2,
 2,
 'Proximity sensors for packaging line. Sensors giving intermittent readings.',
 'approved',
 NOW() - INTERVAL '10 hours',
 NOW() - INTERVAL '8 hours',
 (SELECT id FROM users WHERE employee_id = 'TL001'),
 NULL,
 'Approved. Intermittent sensor issues affecting quality control.',
 NOW() - INTERVAL '10 hours',
 NOW() - INTERVAL '8 hours');

-- Display inserted part requests count
SELECT 'Part requests inserted: ' || COUNT(*) as result FROM part_requests;

