-- Sample Report Technicians (Team Assignments) for CMMS System

INSERT INTO report_technicians (id, report_id, technician_id, role, joined_at, left_at, is_active, created_at, updated_at) VALUES 

-- Team assignments for complex reports requiring multiple technicians

-- Report requiring team assistance (Palletizing robot repair)
(uuid_generate_v4(),
 (SELECT id FROM reports WHERE description LIKE '%Palletizing robot requires major component replacement%'),
 (SELECT id FROM users WHERE employee_id = 'TECH005'),
 'main',
 NOW() - INTERVAL '2 hours',
 NULL,
 true,
 NOW() - INTERVAL '2 hours',
 NOW() - INTERVAL '1 hour'),

(uuid_generate_v4(),
 (SELECT id FROM reports WHERE description LIKE '%Palletizing robot requires major component replacement%'),
 (SELECT id FROM users WHERE employee_id = 'TECH003'),
 'support',
 NOW() - INTERVAL '1.5 hours',
 NULL,
 true,
 NOW() - INTERVAL '1.5 hours',
 NOW() - INTERVAL '1 hour'),

(uuid_generate_v4(),
 (SELECT id FROM reports WHERE description LIKE '%Palletizing robot requires major component replacement%'),
 (SELECT id FROM users WHERE employee_id = 'TECH007'),
 'support',
 NOW() - INTERVAL '1 hour',
 NULL,
 true,
 NOW() - INTERVAL '1 hour',
 NOW() - INTERVAL '1 hour'),

-- Report requiring team assistance (Coordinate measuring machine)
(uuid_generate_v4(),
 (SELECT id FROM reports WHERE description LIKE '%Coordinate measuring machine requires calibration%'),
 (SELECT id FROM users WHERE employee_id = 'TECH004'),
 'main',
 NOW() - INTERVAL '3 hours',
 NULL,
 true,
 NOW() - INTERVAL '3 hours',
 NOW() - INTERVAL '3 hours'),

(uuid_generate_v4(),
 (SELECT id FROM reports WHERE description LIKE '%Coordinate measuring machine requires calibration%'),
 (SELECT id FROM users WHERE employee_id = 'TECH002'),
 'support',
 NOW() - INTERVAL '2.5 hours',
 NULL,
 true,
 NOW() - INTERVAL '2.5 hours',
 NOW() - INTERVAL '3 hours'),

-- Emergency generator repair (high priority, multiple technicians)
(uuid_generate_v4(),
 (SELECT id FROM reports WHERE description LIKE '%Emergency generator electrical panel showing arc flash%'),
 (SELECT id FROM users WHERE employee_id = 'TECH004'),
 'main',
 NOW() - INTERVAL '30 minutes',
 NULL,
 true,
 NOW() - INTERVAL '30 minutes',
 NOW() - INTERVAL '15 minutes'),

(uuid_generate_v4(),
 (SELECT id FROM reports WHERE description LIKE '%Emergency generator electrical panel showing arc flash%'),
 (SELECT id FROM users WHERE employee_id = 'TECH005'),
 'support',
 NOW() - INTERVAL '25 minutes',
 NULL,
 true,
 NOW() - INTERVAL '25 minutes',
 NOW() - INTERVAL '15 minutes'),

(uuid_generate_v4(),
 (SELECT id FROM reports WHERE description LIKE '%Emergency generator electrical panel showing arc flash%'),
 (SELECT id FROM users WHERE employee_id = 'TL001'),
 'leader',
 NOW() - INTERVAL '20 minutes',
 NULL,
 true,
 NOW() - INTERVAL '20 minutes',
 NOW() - INTERVAL '15 minutes'),

-- CNC Machine repair with team support
(uuid_generate_v4(),
 (SELECT id FROM reports WHERE description LIKE '%CNC Machine C1 spindle bearing is making loud noise%'),
 (SELECT id FROM users WHERE employee_id = 'TECH002'),
 'main',
 NOW() - INTERVAL '3 hours',
 NULL,
 true,
 NOW() - INTERVAL '3 hours',
 NOW() - INTERVAL '30 minutes'),

(uuid_generate_v4(),
 (SELECT id FROM reports WHERE description LIKE '%CNC Machine C1 spindle bearing is making loud noise%'),
 (SELECT id FROM users WHERE employee_id = 'TECH001'),
 'support',
 NOW() - INTERVAL '2 hours',
 NULL,
 true,
 NOW() - INTERVAL '2 hours',
 NOW() - INTERVAL '30 minutes'),

-- Historical team assignments (completed reports)

-- Overhead crane maintenance (completed with team)
(uuid_generate_v4(),
 (SELECT id FROM reports WHERE description LIKE '%Overhead crane in warehouse was making grinding noise%'),
 (SELECT id FROM users WHERE employee_id = 'TECH003'),
 'main',
 NOW() - INTERVAL '192 hours',
 NOW() - INTERVAL '144 hours',
 false,
 NOW() - INTERVAL '192 hours',
 NOW() - INTERVAL '144 hours'),

(uuid_generate_v4(),
 (SELECT id FROM reports WHERE description LIKE '%Overhead crane in warehouse was making grinding noise%'),
 (SELECT id FROM users WHERE employee_id = 'TECH008'),
 'support',
 NOW() - INTERVAL '190 hours',
 NOW() - INTERVAL '144 hours',
 false,
 NOW() - INTERVAL '190 hours',
 NOW() - INTERVAL '144 hours'),

-- Welding station repair (completed with assistance)
(uuid_generate_v4(),
 (SELECT id FROM reports WHERE description LIKE '%Welding station B1 gas regulator was not maintaining%'),
 (SELECT id FROM users WHERE employee_id = 'TECH007'),
 'main',
 NOW() - INTERVAL '24 hours',
 NOW() - INTERVAL '12 hours',
 false,
 NOW() - INTERVAL '24 hours',
 NOW() - INTERVAL '12 hours'),

(uuid_generate_v4(),
 (SELECT id FROM reports WHERE description LIKE '%Welding station B1 gas regulator was not maintaining%'),
 (SELECT id FROM users WHERE employee_id = 'TECH005'),
 'support',
 NOW() - INTERVAL '20 hours',
 NOW() - INTERVAL '12 hours',
 false,
 NOW() - INTERVAL '20 hours',
 NOW() - INTERVAL '12 hours'),

-- Grid location repair with team (unusual vibration)
(uuid_generate_v4(),
 (SELECT id FROM reports WHERE description LIKE '%Unusual vibration and noise coming from grid location A2-03%'),
 (SELECT id FROM users WHERE employee_id = 'TECH006'),
 'main',
 NOW() - INTERVAL '1 hour',
 NULL,
 true,
 NOW() - INTERVAL '1 hour',
 NOW() - INTERVAL '30 minutes'),

(uuid_generate_v4(),
 (SELECT id FROM reports WHERE description LIKE '%Unusual vibration and noise coming from grid location A2-03%'),
 (SELECT id FROM users WHERE employee_id = 'TECH001'),
 'support',
 NOW() - INTERVAL '45 minutes',
 NULL,
 true,
 NOW() - INTERVAL '45 minutes',
 NOW() - INTERVAL '30 minutes'),

-- Team assignments that were temporary (technician left the team)
(uuid_generate_v4(),
 (SELECT id FROM reports WHERE description LIKE '%Quality control optical inspection system is showing%'),
 (SELECT id FROM users WHERE employee_id = 'TECH004'),
 'main',
 NOW() - INTERVAL '4 hours',
 NULL,
 true,
 NOW() - INTERVAL '4 hours',
 NOW() - INTERVAL '2 hours'),

(uuid_generate_v4(),
 (SELECT id FROM reports WHERE description LIKE '%Quality control optical inspection system is showing%'),
 (SELECT id FROM users WHERE employee_id = 'TECH002'),
 'support',
 NOW() - INTERVAL '3 hours',
 NOW() - INTERVAL '2.5 hours',
 false,
 NOW() - INTERVAL '3 hours',
 NOW() - INTERVAL '2.5 hours'),

-- Leader involvement in critical repairs
(uuid_generate_v4(),
 (SELECT id FROM reports WHERE description LIKE '%Main air compressor electrical panel showing overheating%'),
 (SELECT id FROM users WHERE employee_id = 'TECH005'),
 'main',
 NOW() - INTERVAL '4 hours',
 NULL,
 true,
 NOW() - INTERVAL '4 hours',
 NOW() - INTERVAL '2 hours'),

(uuid_generate_v4(),
 (SELECT id FROM reports WHERE description LIKE '%Main air compressor electrical panel showing overheating%'),
 (SELECT id FROM users WHERE employee_id = 'TL001'),
 'leader',
 NOW() - INTERVAL '3.5 hours',
 NULL,
 true,
 NOW() - INTERVAL '3.5 hours',
 NOW() - INTERVAL '2 hours'),

(uuid_generate_v4(),
 (SELECT id FROM reports WHERE description LIKE '%Main air compressor electrical panel showing overheating%'),
 (SELECT id FROM users WHERE employee_id = 'TECH004'),
 'support',
 NOW() - INTERVAL '3 hours',
 NULL,
 true,
 NOW() - INTERVAL '3 hours',
 NOW() - INTERVAL '2 hours'),

-- Cross-department collaboration
(uuid_generate_v4(),
 (SELECT id FROM reports WHERE description LIKE '%Forklift 1 hydraulic system is leaking fluid%'),
 (SELECT id FROM users WHERE employee_id = 'TECH008'),
 'main',
 NOW() - INTERVAL '5 hours',
 NULL,
 true,
 NOW() - INTERVAL '5 hours',
 NOW() - INTERVAL '5 hours'),

(uuid_generate_v4(),
 (SELECT id FROM reports WHERE description LIKE '%Forklift 1 hydraulic system is leaking fluid%'),
 (SELECT id FROM users WHERE employee_id = 'TECH005'),
 'support',
 NOW() - INTERVAL '4.5 hours',
 NULL,
 true,
 NOW() - INTERVAL '4.5 hours',
 NOW() - INTERVAL '5 hours'),

-- Training scenarios (experienced technician mentoring)
(uuid_generate_v4(),
 (SELECT id FROM reports WHERE description LIKE '%Grinding machine B2 safety guard is loose%'),
 (SELECT id FROM users WHERE employee_id = 'TECH007'),
 'main',
 NOW() - INTERVAL '45 minutes',
 NULL,
 true,
 NOW() - INTERVAL '45 minutes',
 NOW() - INTERVAL '45 minutes'),

(uuid_generate_v4(),
 (SELECT id FROM reports WHERE description LIKE '%Grinding machine B2 safety guard is loose%'),
 (SELECT id FROM users WHERE employee_id = 'TECH008'),
 'support',
 NOW() - INTERVAL '30 minutes',
 NULL,
 true,
 NOW() - INTERVAL '30 minutes',
 NOW() - INTERVAL '45 minutes');

-- Display inserted report technicians count
SELECT 'Report technicians inserted: ' || COUNT(*) as result FROM report_technicians;

